export * from "./generated/ItsystemsPdDataServicesDataModelModel";

export enum Collection {
  MemberParty = "MemberParty",
  Party = "Party",
  Person = "Person",
  PersonAddress = "PersonAddress",
  PersonCommunication = "PersonCommunication",
  PersonInterest = "PersonInterest",
  Session = "Session",
  Committee = "Committee",
  MemberCommittee = "MemberCommittee",
  Canton = "Canton",
  Council = "Council",
  Objective = "Objective",
  Resolution = "Resolution",
  Publication = "Publication",
  External = "External",
  Meeting = "Meeting",
  Subject = "Subject",
  Citizenship = "Citizenship",
  Preconsultation = "Preconsultation",
  Bill = "Bill",
  BillLink = "BillLink",
  BillStatus = "BillStatus",
  Business = "Business",
  BusinessResponsibility = "BusinessResponsibility",
  BusinessRole = "BusinessRole",
  LegislativePeriod = "LegislativePeriod",
  MemberCouncil = "MemberCouncil",
  MemberParlGroup = "MemberParlGroup",
  ParlGroup = "ParlGroup",
  PersonOccupation = "PersonOccupation",
  RelatedBusiness = "RelatedBusiness",
  BusinessStatus = "BusinessStatus",
  BusinessType = "BusinessType",
  MemberCouncilHistory = "MemberCouncilHistory",
  MemberCommitteeHistory = "MemberCommitteeHistory",
  Vote = "Vote",
  Voting = "Voting",
  SubjectBusiness = "SubjectBusiness",
  Transcript = "Transcript",
  ParlGroupHistory = "ParlGroupHistory",
  Tags = "Tags",
  SeatOrganisationNr = "SeatOrganisationNr",
  PersonEmployee = "PersonEmployee",
  Rapporteur = "Rapporteur",
}

// eslint-disable-next-line
export interface SwissParlEntity {}
